# Generated by Django 5.0.4 on 2024-05-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_siteuser_company_registration_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='kyc_document',
            field=models.FileField(blank=True, upload_to='media/kyc_docs/'),
        ),
    ]
